export const studentData = {
  name: "Aryan Mehta",
  email: "aryan.mehta@university.edu",
  university: "IIT Bombay",
  course: "B.Tech Computer Science",
  year: "3rd Year",
  avatar: "AM",
  jobReadinessScore: 78,
  overallSkillScore: 82,
  githubProfile: "github.com/aryanmehta",
  skills: [
    { skill: "Problem Solving", score: 85 },
    { skill: "Technical Skills", score: 88 },
    { skill: "Communication", score: 72 },
    { skill: "Project Experience", score: 79 },
    { skill: "Industry Readiness", score: 74 },
    { skill: "Collaboration", score: 80 },
  ],
  radarData: [
    { subject: "Algorithms", A: 85, fullMark: 100 },
    { subject: "Web Dev", A: 90, fullMark: 100 },
    { subject: "ML/AI", A: 72, fullMark: 100 },
    { subject: "DevOps", A: 65, fullMark: 100 },
    { subject: "System Design", A: 70, fullMark: 100 },
    { subject: "Communication", A: 78, fullMark: 100 },
  ],
  progressData: [
    { month: "Jan", score: 58 },
    { month: "Feb", score: 63 },
    { month: "Mar", score: 68 },
    { month: "Apr", score: 72 },
    { month: "May", score: 75 },
    { month: "Jun", score: 79 },
    { month: "Jul", score: 82 },
  ],
  careerPaths: [
    { role: "Full Stack Developer", match: 92, salary: "₹12-18 LPA", demand: "Very High" },
    { role: "ML Engineer", match: 78, salary: "₹15-25 LPA", demand: "High" },
    { role: "DevOps Engineer", match: 71, salary: "₹10-16 LPA", demand: "High" },
    { role: "Product Manager", match: 65, salary: "₹14-22 LPA", demand: "Medium" },
  ],
  skillGaps: [
    { skill: "Docker & Kubernetes", priority: "High", timeToLearn: "4 weeks" },
    { skill: "System Design", priority: "High", timeToLearn: "6 weeks" },
    { skill: "GraphQL", priority: "Medium", timeToLearn: "2 weeks" },
    { skill: "Redis", priority: "Medium", timeToLearn: "1 week" },
    { skill: "AWS Services", priority: "High", timeToLearn: "8 weeks" },
  ],
  aiInsights: [
    "Your React and TypeScript proficiency is in the top 15% of candidates.",
    "Consider strengthening cloud infrastructure skills to boost employability by ~18%.",
    "Your GitHub activity shows strong consistency — a key signal for recruiters.",
    "Adding system design projects could increase your industry readiness score significantly.",
  ],
  badges: [
    { name: "Code Warrior", icon: "⚔️", color: "blue" },
    { name: "Problem Solver", icon: "🧩", color: "violet" },
    { name: "Top 10%", icon: "🏆", color: "amber" },
    { name: "Fast Learner", icon: "🚀", color: "cyan" },
  ]
};

export const instituteData = {
  name: "IIT Bombay",
  totalStudents: 2847,
  placedStudents: 2134,
  avgSkillScore: 74,
  topSkill: "Machine Learning",
  skillDistribution: [
    { skill: "Web Development", students: 820, avg: 78 },
    { skill: "Machine Learning", students: 650, avg: 81 },
    { skill: "Data Science", students: 540, avg: 76 },
    { skill: "DevOps", students: 380, avg: 70 },
    { skill: "Mobile Dev", students: 290, avg: 73 },
    { skill: "Cybersecurity", students: 167, avg: 68 },
  ],
  placementTrends: [
    { year: "2020", rate: 72, avgSalary: 8.2 },
    { year: "2021", rate: 75, avgSalary: 9.1 },
    { year: "2022", rate: 79, avgSalary: 10.8 },
    { year: "2023", rate: 83, avgSalary: 12.4 },
    { year: "2024", rate: 87, avgSalary: 14.2 },
  ],
  curriculumGaps: [
    { area: "Cloud Computing", gap: 35, priority: "Critical" },
    { area: "System Design", gap: 28, priority: "High" },
    { area: "AI/ML Ops", gap: 22, priority: "High" },
    { area: "Soft Skills", gap: 18, priority: "Medium" },
    { area: "Blockchain", gap: 15, priority: "Low" },
  ],
  departmentPerformance: [
    { dept: "CSE", score: 82, students: 680 },
    { dept: "ECE", score: 74, students: 520 },
    { dept: "Mech", score: 65, students: 490 },
    { dept: "Civil", score: 61, students: 380 },
    { dept: "Chem", score: 58, students: 310 },
  ],
};

export const industryData = {
  company: "TechCorp India",
  openRoles: 48,
  matchedCandidates: 312,
  avgMatchScore: 76,
  skillDemand: [
    { skill: "React/Next.js", demand: 92, supply: 78, gap: 14 },
    { skill: "Python/ML", demand: 88, supply: 71, gap: 17 },
    { skill: "AWS/Cloud", demand: 85, supply: 58, gap: 27 },
    { skill: "Node.js", demand: 79, supply: 82, gap: -3 },
    { skill: "DevOps", demand: 76, supply: 55, gap: 21 },
    { skill: "Data Engineering", demand: 71, supply: 49, gap: 22 },
  ],
  topCandidates: [
    { name: "Aryan Mehta", score: 92, university: "IIT Bombay", role: "Full Stack Dev" },
    { name: "Priya Singh", score: 89, university: "NIT Trichy", role: "ML Engineer" },
    { name: "Rahul Kumar", score: 87, university: "BITS Pilani", role: "DevOps Engineer" },
    { name: "Sneha Patel", score: 85, university: "IIT Delhi", role: "Data Scientist" },
    { name: "Vikram Nair", score: 83, university: "IIIT Hyderabad", role: "Full Stack Dev" },
  ],
  marketTrends: [
    { month: "Jan", ai: 68, cloud: 72, web: 85 },
    { month: "Feb", ai: 72, cloud: 74, web: 84 },
    { month: "Mar", ai: 78, cloud: 76, web: 83 },
    { month: "Apr", ai: 82, cloud: 79, web: 82 },
    { month: "May", ai: 87, cloud: 82, web: 81 },
    { month: "Jun", ai: 91, cloud: 85, web: 83 },
  ],
};

export const govData = {
  totalStudents: 4200000,
  employmentRate: 68.4,
  skillGapIndex: 32.1,
  topDemandSkills: ["AI/ML", "Cloud", "Cybersecurity", "Data Engineering"],
  stateData: [
    { state: "Maharashtra", students: 680000, employed: 72, score: 76 },
    { state: "Karnataka", students: 520000, employed: 78, score: 81 },
    { state: "Tamil Nadu", students: 490000, employed: 75, score: 78 },
    { state: "Delhi", students: 380000, employed: 80, score: 83 },
    { state: "Telangana", students: 310000, employed: 74, score: 77 },
    { state: "Gujarat", students: 290000, employed: 69, score: 72 },
  ],
  sectorDemand: [
    { sector: "IT Services", demand: 340000, supply: 220000 },
    { sector: "FinTech", demand: 180000, supply: 95000 },
    { sector: "HealthTech", demand: 120000, supply: 60000 },
    { sector: "EdTech", demand: 90000, supply: 75000 },
    { sector: "Manufacturing", demand: 250000, supply: 310000 },
  ],
  forecastData: [
    { year: "2025", demand: 1.8, supply: 1.4, gap: 0.4 },
    { year: "2026", demand: 2.1, supply: 1.6, gap: 0.5 },
    { year: "2027", demand: 2.5, supply: 1.9, gap: 0.6 },
    { year: "2028", demand: 2.9, supply: 2.2, gap: 0.7 },
    { year: "2029", demand: 3.4, supply: 2.6, gap: 0.8 },
  ],
  programEffectiveness: [
    { program: "PMKVY", enrolled: 450000, completed: 380000, employed: 71 },
    { program: "NSDC", enrolled: 320000, completed: 275000, employed: 68 },
    { program: "Skill India", enrolled: 890000, completed: 720000, employed: 65 },
    { program: "DDU-GKY", enrolled: 180000, completed: 145000, employed: 74 },
  ],
};
